apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ttrss-config-pvc
  namespace: ttrss
  labels:
    app: ttrss
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ttrss
  name: ttrss
  namespace: ttrss
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ttrss
  template:
    metadata:
      labels:
        app: ttrss
    spec:
      containers:
      - name: ttrss
        image: linuxserver/tt-rss:19.2-ls15
        env:
          - name: DB_TYPE
            value: pgsql
          - name: DB_USER
            value: postgres
          - name: DB_HOST
            value: db-svc
          - name: DB_NAME
            value: postgres
          - name: DB_PASS
            value: postgres
          - name: DB_PORT
            value: "5432"
          - name: SELF_URL_PATH
            value: https://feeds.underyx.me/
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 32Mi
        volumeMounts:
          - mountPath: /config
            name: ttrss-config
      volumes:
        - name: ttrss-config
          persistentVolumeClaim:
            claimName: ttrss-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ttrss
  name: ttrss-svc
  namespace: ttrss
spec:
  ports:
  - port: 80
  selector:
    app: ttrss
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ttrss-cert
  namespace: ttrss
  labels:
    app: ttrss
spec:
  secretName: ttrss-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: feeds.underyx.me
  dnsNames:
  - feeds.underyx.me
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - feeds.underyx.me
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: ttrss
  name: ttrss-ingress
  namespace: ttrss
spec:
  rules:
  - host: feeds.underyx.me
    http:
      paths:
      - backend:
          serviceName: ttrss-svc
          servicePort: 80
        path: /
  tls:
    - hosts:
      - feeds.underyx.me
      secretName: ttrss-tls
