---
- name: add common repos
  apt_repository: repo={{ item }}
  with_items: "{{ common_apt_repos[ansible_distribution] }}"
  when: ansible_pkg_mgr == 'apt'

- name: install common apt packages
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items: "{{ common_apt_packages }}"
  when: ansible_pkg_mgr == 'apt'

- name: install pipx
  pip: name=pipx state=latest break_system_packages=yes

- name: install/update common python packages
  community.general.pipx: name={{ item }}
  with_items: "{{ common_pipx_packages }}"
