- name: install ufw
  apt: pkg=ufw update_cache=yes state=latest

- name: reset ufw
  ufw:
      state: reset

- name: enable ufw logging
  ufw:
      logging: on

- name: rate limit SSH connections
  ufw:
      rule: limit
      proto: tcp
      port: ssh

- name: allow Kubernetes API server connections
  ufw:
      rule: allow
      proto: tcp
      port: "6443"
      comment: Kubernetes API server

- name: allow etcd server client API connections
  ufw:
      rule: allow
      proto: tcp
      port: "2379:2380"
      comment: etcd server client API

- name: allow Kubelet API, kube-scheduler, kube-controller-manager connections
  ufw:
      rule: allow
      proto: tcp
      port: "10250:10252"
      comment: Kubelet API, kube-scheduler, kube-controller-manager

- name: allow i.underyx.me SFTP connections
  ufw:
      rule: allow
      proto: tcp
      port: "30464"
      comment: i.underyx.me SFTP

- name: allow HTTP
  ufw:
      rule: allow
      proto: tcp
      port: http

- name: allow HTTPS
  ufw:
      rule: allow
      proto: tcp
      port: https

- name: allow BitTorrent transport
  ufw:
      rule: allow
      proto: tcp
      port: "45401:45405"
      comment: BitTorrent transport

- name: allow BitTorrent control
  ufw:
      rule: allow
      proto: udp
      port: "45401:45405"
      comment: BitTorrent control

- name: enable ufw
  ufw:
      state: enabled
