- name: apply flannel
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml
  become_user: "{{ user }}"

- name: allow scheduling on master node
  command: kubectl taint nodes --all node-role.kubernetes.io/master-
  become_user: "{{ user }}"
