- name: create /tmp/k8s-manifests
  file: path=/tmp/k8s-manifests state=directory

- name: allow scheduling on master node
  command: kubectl taint nodes --all node-role.kubernetes.io/master-
  ignore_errors: yes

- name: apply flannel
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml

- name: install helm
  shell: curl https://raw.githubusercontent.com/helm/helm/v2.11.0/scripts/get | bash
  args:
    warn: no

- name: copy helm tiller role
  copy: src=helm-tiller-role.yml dest=/tmp/k8s-manifests/helm-tiller-role.yml

- name: apply helm tiller role
  command: kubectl apply -f /tmp/k8s-manifests/helm-tiller-role.yml

- name: install helm tiller
  command: helm init --service-account tiller

- name: install cert-manager
  command: helm install --name cert-manager --namespace kube-system stable/cert-manager
  ignore_errors: yes

- name: copy cloudflare-issuer config
  copy: src=cert-manager-issuers.yml dest=/tmp/k8s-manifests/cert-manager-issuers.yml

- name: apply cloudflare-issuer config
  command: kubectl apply -f /tmp/k8s-manifests/cert-manager-issuers.yml

- name: copy ingress config
  copy: src=ingress.yml dest=/tmp/k8s-manifests/ingress.yml

- name: apply ingress
  command: kubectl apply -f /tmp/k8s-manifests/ingress.yml

- name: apply dashboard
  command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.0/src/deploy/recommended/kubernetes-dashboard.yaml

- name: copy rook operator
  copy: src=rook-operator.yml dest=/tmp/k8s-manifests/rook-operator.yml

- name: apply rook operator
  command: kubectl apply -f /tmp/k8s-manifests/rook-operator.yml

- name: wait for rook operator to be deployed
  command: kubectl rollout status -n rook-ceph-system deployment rook-ceph-operator

- name: copy rook config
  copy: src=rook-cluster.yml dest=/tmp/k8s-manifests/rook-cluster.yml

- name: apply rook config
  command: kubectl apply -f /tmp/k8s-manifests/rook-cluster.yml

- name: copy rook pool
  copy: src=rook-pool.yml dest=/tmp/k8s-manifests/rook-pool.yml

- name: apply rook pool
  command: kubectl apply -f /tmp/k8s-manifests/rook-pool.yml

- name: copy rook tools
  copy: src=rook-tools.yml dest=/tmp/k8s-manifests/rook-tools.yml

- name: apply rook tools
  command: kubectl apply -f /tmp/k8s-manifests/rook-tools.yml

