- name: copy system manifests
  copy: src=manifests/system dest=/tmp/manifests

- name: apply flannel
  command: kubectl apply -f /tmp/manifests/system/flannel

- name: apply cert-manager config
  command: kubectl apply -f /tmp/manifests/system/cert-manager

- name: apply nginx-ingress
  command: kubectl apply -f /tmp/manifests/system/nginx-ingress

- name: apply dashboard
  command: kubectl apply -f /tmp/manifests/system/kubernetes-dashboard

- name: apply rook operator
  command: kubectl apply -f /tmp/manifests/system/rook/operator.yml

- name: wait for rook operator to be deployed
  command: kubectl rollout status -n rook-ceph-system deployment rook-ceph-operator

- name: apply rook
  command: kubectl apply -f /tmp/manifests/system/rook
