- name: download dotfiles repo
  git: repo=https://github.com/underyx/dotfiles dest=~/dotfiles

- name: install dotfiles
  command: ~/dotfiles/install

- name: create local environment file
  file: path=~/.zshlocal/pre/environment state=touch
