apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:v0.5.17
        args:
        - --source=ingress
        - --provider=cloudflare
        - --registry=txt
        - --txt-owner-id=unicorn
        - --log-level=debug
        env:
        - name: CF_API_EMAIL
          value: underer@gmail.com
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-key
              key: key
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 16Mi
