apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: rustic-encryption-password
  namespace: immich
spec:
  itemPath: "vaults/aurora/items/rustic-encryption-password"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: rustic-scaleway-credentials
  namespace: immich
spec:
  itemPath: "vaults/aurora/items/rustic-scaleway-credentials"
