apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: immich
  namespace: kube-system
spec:
  repo: https://immich-app.github.io/immich-charts
  chart: immich
  targetNamespace: immich
  valuesContent: |-
    env:
      DB_HOSTNAME:
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: host
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: username
      DB_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: dbname
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: password
    image:
      tag: v1.126.1
    server:
      ingress:
        main:
          enabled: true
          hosts:
          - host: photos.bence.dev
            paths:
              - path: "/"
          annotations:
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
            traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    immich:
      persistence:
        library:
          existingClaim: immich-pvc
      metrics:
        enabled: false
    redis:
      enabled: true
