apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: immich
  namespace: kube-system
spec:
  repo: https://immich-app.github.io/immich-charts
  chart: immich
  targetNamespace: immich
  valuesContent: |-
    image:
      tag: v1.121.0
    server:
      ingress:
        main:
          enabled: true
          hosts:
          - host: photos.bence.dev
            paths:
              - path: "/"
          annotations:
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
            traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    immich:
      persistence:
        library:
          existingClaim: immich-pvc
      metrics:
        enabled: false
    postgresql:
      enabled: true
      image:
        tag: pg16-v0.2.1
      primary:
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi
    redis:
      enabled: true
