apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: immich
  namespace: kube-system
spec:
  repo: https://immich-app.github.io/immich-charts
  chart: immich
  targetNamespace: immich
  valuesContent: |-
    image:
      tag: v1.106.4
    ingress:
      main:
        enabled: true
        hostname: photos.bence.dev
        annotations:
          traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    immich:
      persistence:
        library:
          existingClaim: immich-pvc
      metrics:
        enabled: false
    postgresql:
      enabled: true
      image:
        tag: pg16-v0.2.1
    redis:
      enabled: true
