kind: Deployment
apiVersion: apps/v1
metadata:
  name: miniflux
  namespace: miniflux
  labels:
    app: miniflux
spec:
  replicas: 2
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      annotations:
        operator.1password.io/item-path: "vaults/aurora/items/miniflux-admin-password"
        operator.1password.io/item-name: miniflux-admin-password
      labels:
        app: miniflux
    spec:
      containers:
        - name: app
          image: miniflux/miniflux:2.1.3
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: miniflux-db-app
                  key: uri
            - name: RUN_MIGRATIONS
              value: "1"
            - name: CREATE_ADMIN
              value: "1"
            - name: BASE_URL
              value: "https://news.bence.dev/"
            - name: HTTPS
              value: "1"
            - name: ADMIN_USERNAME
              value: underyx
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: miniflux-admin-password
                  key: credential
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 64Mi
---
kind: Service
apiVersion: v1
metadata:
  name: miniflux-svc
  namespace: miniflux
spec:
  selector:
    app: miniflux
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: miniflux-ingress
  namespace: miniflux
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  rules:
    - host: news.bence.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: miniflux-svc
                port:
                  number: 8080
