common_apt_repos:
  Ubuntu:
    - ppa:neovim-ppa/unstable

common_apt_packages:
  - curl
  - git
  - htop
  - neovim
  - python3-pip
  - python3-venv
  - tmux
  - zsh

common_pipx_packages:
  - httpie
  - poetry
  - pre-commit
