---
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: media-fs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 1
  dataPools:
    - replicated:
        size: 1
  metadataServer:
    activeCount: 1
    activeStandby: true
