---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: media
  labels:
    app: radarr
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: radarr
  namespace: media
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: app
        image: linuxserver/radarr:134
        ports:
        - containerPort: 7878
        env:
          - name: PUID
            value: "797"
          - name: PGID
            value: "797"
        volumeMounts:
        - name: radarr-config
          mountPath: /config
        - name: radarr-media
          mountPath: /media
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: rtc
          mountPath: /dev/rtc
          readOnly: true
        livenessProbe:
          httpGet:
            path: /
            port: 7878
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: radarr-config
        persistentVolumeClaim:
          claimName: radarr-config-pvc
      - name: radarr-media
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: media-fs
            clusterNamespace: rook-ceph
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: rtc
        hostPath:
          path: /dev/rtc
      securityContext:
        fsGroup: 797
---
kind: Service
apiVersion: v1
metadata:
  name: radarr-svc
  namespace: media
spec:
  ports:
    - port: 80
      targetPort: 7878
  selector:
    app: radarr
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: radarr-cert
  namespace: media
  labels:
    app: radarr
spec:
  secretName: radarr-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: radarr.underyx.me
  dnsNames:
  - radarr.underyx.me
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - radarr.underyx.me
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: radarr-ingress
  namespace: media
spec:
  rules:
  - host: radarr.underyx.me
    http:
      paths:
      - backend:
          serviceName: radarr-svc
          servicePort: 80
        path: /
  tls:
  - hosts:
    - radarr.underyx.me
    secretName: radarr-tls
