apiVersion: v1
kind: PersistentVolume
metadata:
  name: obsidian-pv
  namespace: obsidian
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /mnt/nfs_share/obsidian-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - aurora.bence.dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-pvc
  namespace: obsidian
spec:
  volumeName: obsidian-pv
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
