# MIT License - Copyright (c) 2019 Karan Sharma
# https://github.com/mr-karan/hydra

- name: Update apt cache and upgrade
  apt:
    update_cache: yes
    upgrade: "yes"

- name: Tailscale Signing Key
  apt_key:
    url: https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.gpg
    state: present

- name: Add Tailscale Deb
  apt_repository:
    repo: deb https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} main
    state: present

- name: Install Tailscale
  apt:
    name: tailscale
    state: present
    update_cache: yes
  notify: enable tailscaled service

- name: Check if Tailscale is connected
  command: tailscale status
  changed_when: false
  register: tailscale_status

# https://tailscale.com/kb/1104/enable-ip-forwarding
- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
