# https://www.nomadproject.io/docs/install/production/requirements

- name: allow Nomad HTTP API
  ufw:
    rule: allow
    proto: tcp
    port: "4646"
    comment: Nomad HTTP API

- name: allow Nomad RPC
  ufw:
    rule: allow
    proto: tcp
    port: "4647"
    comment: Nomad RPC

- name: allow Serf WAN TCP
  ufw:
    rule: allow
    proto: tcp
    port: "4648"
    comment: Nomad Serf WAN TCP

- name: allow Serf WAN UDP
  ufw:
    rule: allow
    proto: udp
    port: "4648"
    comment: Nomad Serf WAN UDP

- name: allow Nomad cluster services TCP
  ufw:
    rule: allow
    proto: tcp
    port: "20000:32000"
    comment: Nomad cluster services TCP

- name: allow Nomad cluster services UDP
  ufw:
    rule: allow
    proto: udp
    port: "20000:32000"
    comment: Nomad cluster services UDP
