- name: add hashicorp apt key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg

- name: add hashicorp apt repo
  apt_repository:
    repo: >
      deb [arch=amd64] https://apt.releases.hashicorp.com
      {{ ansible_distribution_release | lower }} main

- name: install nomad
  apt: pkg=nomad update_cache=yes state=latest

- name: create nomad directory
  file:
    path: /opt/nomad
    state: directory
    owner: root
    group: root

- name: create nomad service config
  copy:
    src: nomad.service
    dest: /etc/systemd/system/nomad.service
    owner: root
    group: root
    mode: 0644
  notify: restart nomad

- name: create nomad config file
  copy:
    src: nomad.hcl
    dest: /etc/nomad.d/nomad.hcl
    owner: root
    group: root
    mode: 0600
  notify: restart nomad

- name: set nomad to start on launch
  service: name=nomad enabled=yes
