---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-pvc
  namespace: media
  labels:
    app: bazarr
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bazarr
  namespace: media
  labels:
    app: bazarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
        - name: app
          image: linuxserver/bazarr:74079bc4-ls63
          ports:
            - containerPort: 6767
          env:
            - name: PUID
              value: "797"
            - name: PGID
              value: "797"
          volumeMounts:
            - name: bazarr-config
              mountPath: /config
            - name: bazarr-media
              mountPath: /media
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: rtc
              mountPath: /dev/rtc
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 6767
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 256Mi
      volumes:
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: bazarr-config-pvc
        - name: bazarr-media
          persistentVolumeClaim:
            claimName: media-pvc
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: rtc
          hostPath:
            path: /dev/rtc
      securityContext:
        fsGroup: 797
---
kind: Service
apiVersion: v1
metadata:
  name: bazarr-svc
  namespace: media
spec:
  ports:
    - port: 80
      targetPort: 6767
  selector:
    app: bazarr
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bazarr-ingress
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: bazarr.underyx.me
      http:
        paths:
          - backend:
              serviceName: bazarr-svc
              servicePort: 80
            path: /
  tls:
    - hosts:
        - bazarr.underyx.me
      secretName: bazarr-tls
