apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config-pvc
  namespace: media
  labels:
    app: jackett
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jackett
  namespace: media
  labels:
    app: jackett
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
        - name: app
          image: lscr.io/linuxserver/jackett:latest
          ports:
            - name: http
              containerPort: 9117
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 9117
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jackett-config-pvc
        - name: localtime
          hostPath:
            path: /etc/localtime
      securityContext:
        fsGroup: 797
---
kind: Service
apiVersion: v1
metadata:
  name: jackett-svc
  namespace: media
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: jackett
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett-ingress
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  rules:
    - host: jackett.bence.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: jackett-svc
                port:
                  name: http
