apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: media
  labels:
    app: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: plex
  namespace: media
  labels:
    app: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: app
          image: plexinc/pms-docker:public
          ports:
            - containerPort: 32400
              hostPort: 32400
          env:
            - name: TZ
              value: America/Los_Angeles
            - name: PLEX_UID
              value: "1000"
            - name: PLEX_GID
              value: "1000"
            - name: PLEX_CLAIM
              valueFrom:
                secretKeyRef:
                  name: plex-env
                  key: PLEX_CLAIM
            - name: ADVERTISE_IP
              value: plex.bence.dev:443
          volumeMounts:
            - name: plex-config
              mountPath: /config
            - name: plex-media
              mountPath: /media
            - name: plex-transcode
              mountPath: /transcode
          livenessProbe:
            tcpSocket:
              port: 32400
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            limits:
              cpu: 4000m
              memory: 4Gi
            requests:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-config-pvc
        - name: plex-transcode
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
        - name: plex-media
          persistentVolumeClaim:
            claimName: media-pvc
      securityContext:
        fsGroup: 1000
---
kind: Service
apiVersion: v1
metadata:
  name: plex-svc
  namespace: media
spec:
  selector:
    app: plex
  ports:
    - name: plex
      port: 32400
      targetPort: 32400
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  rules:
    - host: plex.bence.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: plex-svc
                port:
                  number: 32400
