apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data-pvc
  namespace: media
  labels:
    app: plex
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: plex
  namespace: media
  labels:
    app: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      initContainers:
        - name: set-up-filesystem-mount
          image: busybox:1
          command: ["mkdir", "-p", "/fs/media"]
          volumeMounts:
            - name: fs-root
              mountPath: /fs
      containers:
        - name: app
          image: plexinc/pms-docker:public
          ports:
            - containerPort: 3005
              hostPort: 3005
            - containerPort: 8324
              hostPort: 8324
            - containerPort: 32400
              hostPort: 32400
            - containerPort: 32469
              hostPort: 32469
            - containerPort: 1900
              hostPort: 1900
              protocol: UDP
            - containerPort: 32410
              hostPort: 32410
              protocol: UDP
            - containerPort: 32412
              hostPort: 32412
              protocol: UDP
            - containerPort: 32413
              hostPort: 32413
              protocol: UDP
            - containerPort: 32414
              hostPort: 32414
              protocol: UDP
          env:
            - name: TZ
              value: Europe/Prague
            - name: PLEX_UID
              value: "797"
            - name: PLEX_GID
              value: "797"
            - name: PLEX_CLAIM
              valueFrom:
                secretKeyRef:
                  name: plex-env
                  key: PLEX_CLAIM
            - name: ADVERTISE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: plex-config
              mountPath: /config
            - name: plex-media
              mountPath: /media
            - name: plex-transcode
              mountPath: /transcode
          livenessProbe:
            tcpSocket:
              port: 32400
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            limits:
              cpu: 4000m
              memory: 2Gi
            requests:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-data-pvc
        - name: plex-transcode
          emptyDir: {}
        - name: fs-root
          flexVolume:
            driver: ceph.rook.io/rook
            fsType: ceph
            options:
              fsName: media-fs
              clusterNamespace: rook-ceph
              path: /
        - name: plex-media
          flexVolume:
            driver: ceph.rook.io/rook
            fsType: ceph
            options:
              fsName: media-fs
              clusterNamespace: rook-ceph
              path: /media
      securityContext:
        fsGroup: 797
---
kind: Service
apiVersion: v1
metadata:
  name: plex-svc
  namespace: media
spec:
  selector:
    app: plex
  ports:
    - name: "80"
      port: 80
      targetPort: 32400
    - name: "3005"
      port: 3005
      targetPort: 3005
    - name: "8324"
      port: 8324
      targetPort: 8324
    - name: "32469"
      port: 32469
      targetPort: 32469
    - name: "1900"
      port: 1900
      targetPort: 1900
      protocol: UDP
    - name: "32410"
      port: 32410
      targetPort: 32410
      protocol: UDP
    - name: "32412"
      port: 32412
      targetPort: 32412
      protocol: UDP
    - name: "32413"
      port: 32413
      targetPort: 32413
      protocol: UDP
    - name: "32414"
      port: 32414
      targetPort: 32414
      protocol: UDP
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: plex-cert
  namespace: media
  labels:
    app: plex
spec:
  secretName: plex-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: plex.underyx.me
  dnsNames:
    - plex.underyx.me
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - plex.underyx.me
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: media
spec:
  rules:
    - host: plex.underyx.me
      http:
        paths:
          - backend:
              serviceName: plex-svc
              servicePort: 80
            path: /
  tls:
    - hosts:
        - plex.underyx.me
      secretName: plex-tls
