apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: media
  labels:
    app: radarr
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: radarr
  namespace: media
  labels:
    app: radarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: app
          image: linuxserver/radarr:3.0.0.2585-ls1
          ports:
            - containerPort: 7878
          env:
            - name: PUID
              value: "797"
            - name: PGID
              value: "797"
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: radarr-media
              mountPath: /media
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: rtc
              mountPath: /dev/rtc
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 7878
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 256Mi
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: radarr-media
          persistentVolumeClaim:
            claimName: media-pvc
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: rtc
          hostPath:
            path: /dev/rtc
      securityContext:
        fsGroup: 797
---
kind: Service
apiVersion: v1
metadata:
  name: radarr-svc
  namespace: media
spec:
  ports:
    - port: 80
      targetPort: 7878
  selector:
    app: radarr
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: radarr-ingress
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: radarr.underyx.me
      http:
        paths:
          - backend:
              serviceName: radarr-svc
              servicePort: 80
            path: /
  tls:
    - hosts:
        - radarr.underyx.me
      secretName: radarr-tls
