kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: outline-pvc
  namespace: outline
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-cephfs
