apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: outline
  name: shadowbox-manager
  labels:
    app: shadowbox-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: shadowbox-manager
  template:
    metadata:
      labels:
        app: shadowbox-manager
    spec:
      initContainers:
      - name: install
        image: busybox
        command: ["/bin/sh"]
        args:
        - -c
        - >
          echo '{"rollouts":[{"id":"single-port","enabled":true}],"portForNewAccessKeys":54634}' > /tmp/shadowbox_server_config.json;
            
          if [ ! -f /tmp/shadowbox_config.json ]; then
            echo '{"defaultPort":54634,"accessKeys":[],"nextId":0}' > /tmp/shadowbox_config.json;
          fi
        volumeMounts:
        - name: shadowbox-config
          mountPath: /tmp
      containers:
      - name: manager
        image: quay.io/outline/shadowbox:daily-2020-02-19
        env:
        - name: SB_CERTIFICATE_FILE
          value: "/tmp/shadowbox-selfsigned-dev.crt"
        - name: SB_PRIVATE_KEY_FILE
          value: "/tmp/shadowbox-selfsigned-dev.key"
        - name: SB_PUBLIC_IP
          value: "144.76.111.239"
        - name: SB_API_PORT
          value: "54638"
        - name: SB_API_PREFIX
          value: api
        volumeMounts:
        - name: shadowbox-config
          mountPath: /root/shadowbox/persisted-state
        - name: server-config-volume
          mountPath: /cache
        - name: tls
          mountPath: /tmp/shadowbox-selfsigned-dev.crt
          subPath: shadowbox-selfsigned-dev.crt
        - name: tls
          mountPath: /tmp/shadowbox-selfsigned-dev.key
          subPath: shadowbox-selfsigned-dev.key
        ports:
        - containerPort: 54638
          hostPort: 54638
      volumes:
      - name: server-config-volume
        emptyDir: {}
      - name: shadowbox-config
        persistentVolumeClaim:
          claimName: outline-pvc
      - name: tls
        secret:
          secretName: shadowbox-tls
          items:
          - key: tls.crt
            path: shadowbox-selfsigned-dev.crt
          - key: tls.key
            path: shadowbox-selfsigned-dev.key
