---
- name: add common repos
  apt_repository: repo={{ item }}
  with_items: '{{ common_apt_repos[ansible_os_family] }}'
  when: ansible_pkg_mgr == 'apt'

- name: install common deb packages
  apt: deb={{ item }}
  with_items: '{{ common_deb_packages[ansible_os_family] }}'

- name: install common apt packages
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items: '{{ common_apt_packages }}'
  when: ansible_pkg_mgr == 'apt'

- name: install/update common python 2 packages
  pip: name={{ item }} executable=pip2 state=latest
  with_items: '{{ common_pip2_packages }}'

- name: install/update common python 3 packages
  pip: name={{ item }} executable=pip3 state=latest
  with_items: '{{ common_pip3_packages }}'
