---
- name: Install NFS client packages
  apt:
    name: nfs-common
    state: present

- name: Create local mount point for NFS
  file:
    path: "{{ nfs_client_mount_path }}"
    state: directory
    mode: "0777"

- name: Mount NFS directory
  mount:
    path: "{{ nfs_client_mount_path }}"
    src: "{{ hostvars[nfs_server_host]['private_ip'] | regex_replace('(/24)','') }}:{{ nfs_server_mount_path }}"
    fstype: nfs
    opts: defaults
    state: mounted
