---
- hosts: all
  roles:
   - common
   - ssh
   - ntp
   - { role: apt, when: ansible_pkg_mgr == 'apt' }
   - dotfiles
  become: yes

- hosts: all
  roles:
   - dotfiles
  become: yes
  become_user: underyx
