- name: "Maintenance tasks"
  hosts: hosted
  tasks:
    - name: "apt update"
      apt:
        update_cache: true
    - name: "apt upgrade"
      apt:
        upgrade: true
    - name: "apt autoremove"
      apt:
        autoremove: true
    - name: "apt autoclean"
      apt:
        autoclean: true
  become: true
