kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: archive-warrior
  namespace: default
  labels:
    app: archive-warrior
spec:
  replicas: 2
  selector:
    matchLabels:
      app: archive-warrior
  template:
    metadata:
      labels:
        app: archive-warrior
    spec:
      containers:
      - name: app
        image: archiveteam/warrior-dockerfile
        env:
          - name: DOWNLOADER
            value: underyx
          - name: SELECTED_PROJECT
            value: auto
          - name: CONCURRENT_ITEMS
            value: "8"
