apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: znc-config-pvc
  namespace: default
  labels:
    app: znc
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: znc
  namespace: default
  labels:
    app: znc
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: znc
  template:
    metadata:
      labels:
        app: znc
    spec:
      containers:
        - name: app
          image: znc:1.7-slim
          ports:
            - containerPort: 6697
              hostPort: 6697
          volumeMounts:
            - name: znc-config
              mountPath: /znc-data
          livenessProbe:
            tcpSocket:
              port: 6697
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: znc-config
          persistentVolumeClaim:
            claimName: znc-config-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: znc-svc
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 6697
    - name: irc
      port: 6697
      targetPort: 6697
  selector:
    app: znc
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: znc-cert
  namespace: default
  labels:
    app: znc
spec:
  secretName: znc-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: znc.underyx.me
  dnsNames:
    - znc.underyx.me
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - znc.underyx.me
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: znc-ingress
  namespace: default
spec:
  rules:
    - host: znc.underyx.me
      http:
        paths:
          - backend:
              serviceName: znc-svc
              servicePort: 80
            path: /
  tls:
    - hosts:
        - znc.underyx.me
      secretName: znc-tls
